packages:
  - "packages/*"
  - "integrations/*"
  - "documentation"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  core-js: true
  esbuild: true
  prisma: true
  sharp: true
  vue-demi: true
supportedArchitectures:
  os:
    - current
  cpu:
    - current
  arch:
    - current
sharedWorkspaceLockfile: false
shamefullyHoist: true
preferLocal: true
