import { ArkosConfig } from "../exports";
// import { PrismaClient } from "../generated";
import ExitError from "./helpers/exit-error";

/**
 * Defines and validates the Arkos configuration, filling in defaults where needed.
 * Use this in your `arkos.config.ts` to get full type safety and autocompletion.
 *
 * @example
 * ```ts
 * // arkos.config.ts
 * import prisma from "./src/utils/prisma";
 * import { defineConfig } from "arkos";
 *
 * export default defineConfig({
 *   prisma: { instance: prisma },
 *   globalPrefix: "/api",
 * });
 * ```
 *
 * @see {@link https://www.arkosjs.com/docs/api-reference/define-config}
 */
export function defineConfig(config: ArkosConfig): ArkosConfig {
  // if (!config.prisma?.instance && typeof jest === "undefined") {
  //   throw ExitError(
  //     "ArkosConfigError: prisma.instance is required. Pass your PrismaClient instance via defineConfig({ prisma: { instance: new PrismaClient() } })."
  //   );
  // }

  // if (
  //   !(config.prisma?.instance instanceof PrismaClient) &&
  //   typeof jest === "undefined"
  // ) {
  //   throw ExitError(
  //     "ArkosConfigError: prisma.instance must be a valid PrismaClient instance."
  //   );
  // }

  const finalConfig = {
    welcomeMessage:
      "Welcome to our RESTful API generated by Arkos, find out more about Arkos at www.arkosjs.com",
    globalPrefix: "/api",
    ...config,
    port:
      config.port ||
      Number(process.env.__PORT || process.env.CLI_PORT || process.env.PORT) ||
      8000,
    host:
      config.host ||
      process.env.__HOST ||
      process.env.CLI_HOST ||
      process.env.HOST ||
      (process.env.ARKOS_BUILD !== "true" ? "0.0.0.0" : "127.0.0.1"),
    request: {
      ...config.request,
      parameters: {
        allowDangerousPrismaQueryOptions:
          config.request?.parameters?.allowDangerousPrismaQueryOptions ?? false,
        ...config.request?.parameters,
      },
    },
    fileUpload: {
      baseUploadDir: "uploads",
      baseRoute: "/api/uploads",
      ...config.fileUpload,
    },
    routers: {
      strict: config.routers?.strict || "no-bulk",
      ...config.routers,
    },
    middlewares: {
      ...config.middlewares,
    },
    debugging: {
      requests: {
        level: config.debugging?.requests?.level || 1,
        ...config.debugging?.requests,
      },
    },
  };

  (finalConfig as any).__loader = "defineConfig";

  return finalConfig;
}

export type UserArkosConfig = ReturnType<typeof defineConfig> & {
  __loader: "defineConfig";
};
