blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Uanela/arkos/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://arkosjs.com
    about: Check our comprehensive documentation
