import { Router } from "express";
import swaggerUi from "swagger-ui-express";
import { ArkosConfig } from "../../types/arkos-config";
import deepmerge from "../../utils/helpers/deepmerge.helper";

const swaggerRouter = Router();

export function getSwaggerRouter(arkosConfig: ArkosConfig) {
  const swaggerConfigs: ArkosConfig["swagger"] = deepmerge(
    {
      endpoint: "/docs",
      options: {
        definition: {
          openapi: "3.0.0",
          info: {
            title: "API Generated By Arkos.js",
            version: "1.0.0",
            description:
              "This API was automatically generated by Arkos.js read more about at www.arkosjs.com",
          },
          servers: [
            { url: "http://localhost:8000", description: "Local server" },
          ],
        },
        apis: [
          "./src/routers/*.router.{ts,js}",
          "./src/modules/**/*.router.{ts,js}",
        ],
        deepLinking: true,
        tryItOutEnabled: true,
      },
    },
    arkosConfig.swagger || {}
  );

  swaggerRouter.get("/docs", swaggerUi.serve);

  return swaggerRouter;
}
