services:
  swagger-test-postgres:
    env_file:
      - .env
    user: root
    image: postgres:15.3-alpine
    container_name: swagger-test
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  swagger-test-pgadmin:
    user: root
    image: dpage/pgadmin4:latest
    container_name: swagger-test-pgadmin
    restart: always
    depends_on:
      - swagger-test-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
