import { IncomingMessage, Server, ServerResponse } from "http";
import AppError from "./modules/error-handler/utils/app-error";
import { Express } from "express";
import { bootstrap } from "./app";
import { ArkosConfig } from "./types/arkos-config";
import deepmerge from "./utils/helpers/deepmerge.helper";

process.on("uncaughtException", (err) => {
  console.error("UNCAUGHT EXCEPTION! SHUTTING DOWN...");
  console.error(err.name, err.message);
  console.error(err);
  process.exit(1);
});

let server: Server<typeof IncomingMessage, typeof ServerResponse>;
let _app: Express;
let _arkosConfig: ArkosConfig = {
  welcomeMessage:
    "Welcome to our RESTful API generated by Arkos, find out more about Arkos at www.arkosjs.com",
  authentication: false,
  port: Number(process.env.PORT) || 8000,
};

/**
 * Initializes the application server.
 *
 * This function starts the server by listening on a specified port.
 * The port is determined by the following order of precedence:
 * 1. The `PORT` environment variable.
 * 2. The `port` argument passed to the function.
 * 3. Defaults to `8000` if neither is provided.
 *
 * @param {ArkosConfig} arkosConfig - initial configs for the api ( authentication, port).
 * @returns {Promise<void>} This function does not return a value.
 */
async function initApp(arkosConfig: ArkosConfig = {}): Promise<void> {
  _arkosConfig = deepmerge(_arkosConfig, arkosConfig);

  const port = Number(process.env.PORT) || _arkosConfig.port || 8000;
  _app = await bootstrap(_arkosConfig);

  server = _app.listen(port, () => {
    const time = new Date().toTimeString().split(" ")[0];
    console.info(
      `[\x1b[32mREADY\x1b[0m] \x1b[90m${time}\x1b[0m App running on port \x1b[33m${port}\x1b[0m, server waiting on http://localhost:${port}`
    );

    if (!!process.env.NODE_ENV)
      console.log(`${`Environment: ${process.env.NODE_ENV}`}`);
  });
}

// process.nextTick(() => {
//   const version = JSON.parse(
//     fs.readFileSync(path.join(__dirname, "../../package.json"), "utf8")
//   ).version;

//   console.info(`🚀 Arkos.js v${version}`);
//   // console.info(`   - Local: http://localhost:${port}`);
//   console.info(
//     `${!!process.env.NODE_ENV && `   - Environment: ${process.env.NODE_ENV}`}`
//   );
//   console.info(" ");
// });

process.on("unhandledRejection", (err: AppError) => {
  console.error("UNHANDLED REJECTION! SHUTTING DOWN...");
  console.error(err.name, err.message);
  server.close(() => {
    process.exit(1);
  });
});

export function getArkosConfig() {
  return _arkosConfig;
}

export function getExpressApp() {
  return _app;
}

export { server, initApp };
