name: Deploy to VPS

on:
  push:
    branches:
      - main
    paths:
      'packages/docs/**'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            sudo -u uanela -H bash -c "
              cd /home/***/apps/nodejs/arkosjs.com 
              git config --global --add safe.directory /home/***/apps/nodejs/arkosjs.com
              git reset --hard
              git pull origin main --force
              pnpm install
              pnpm run build
              pm2 restart arkosjs.com
              sudo service nginx restart arkosjs.com.conf
            "
          EOF
